- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disbale old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -
    
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading the Catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      path: /tmp

  - name: unarchiving application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: setup catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: installing mongodb client
    ansible.builtin.dnf:
      name: mongodb-org-shell
      state: present

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.venky.shop --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: Loading catalogue data
    ansible.builtin.command: mongo --host mongodb.venky.shop </app/schema/catalogue.js
    when: product_count.stdout == "0"

  - name: starting and enabling catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enable: yes