- name: Install Redis on CentOS 8
  hosts: redis
  become: yes
 
  tasks:
    - name: Fix CentOS 8 repos (Vault)
      ansible.builtin.shell: |
        sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
 
    - name: Enable PowerTools repo
      ansible.builtin.shell: |
        dnf config-manager --set-enabled powertools || true
 
    - name: Install EPEL repo
      ansible.builtin.dnf:
        name: epel-release
        state: present
 
    - name: Install Remi repo (generic)
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: yes
 
    - name: Enable Redis 6.2 module
      ansible.builtin.command:
        cmd: dnf module enable redis:remi-6.2 -y
 
    - name: Install Redis
      ansible.builtin.dnf:
        name: redis
        state: present
 
    - name: Allow remote connections
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^bind 127.0.0.1'
        replace: 'bind 0.0.0.0'
 
    - name: Disable protected mode
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode yes'
        replace: 'protected-mode no'
 
    - name: Start and enable Redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes