- name: Install and Configure Redis on CentOS Stream 8
  hosts: redis
  become: yes
 
  vars:
    redis_bind_address: 0.0.0.0
    redis_port: 6379
 
  tasks:
 
    ############################################################
    # CLEAN YUM CACHE (repos already fixed)
    ############################################################
    - name: Clean yum cache
      command: yum clean all
      changed_when: false
 
    ############################################################
    # ENABLE REDIS MODULE (AppStream)
    ############################################################
    - name: Enable Redis module
      command: dnf module enable redis -y
      changed_when: false
 
    ############################################################
    # INSTALL REDIS
    ############################################################
    - name: Install Redis
      yum:
        name: redis
        state: present
 
    ############################################################
    # CONFIGURE REDIS
    ############################################################
    - name: Configure Redis bind address
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: "bind {{ redis_bind_address }}"
        backup: yes
 
    - name: Configure Redis port
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^port'
        line: "port {{ redis_port }}"
        backup: yes
 
    ############################################################
    # START SERVICE
    ############################################################
    - name: Start and enable Redis
      service:
        name: redis
        state: started
        enabled: yes