- name: Install Redis on CentOS 8 (AppStream)
  hosts: redis
  become: yes
 
  tasks:
    - name: Fix CentOS 8 repos (Vault)
      shell: |
        sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
 
    - name: Enable Redis module from AppStream
      command: dnf module enable redis -y
 
    - name: Install Redis
      dnf:
        name: redis
        state: present
 
    - name: Allow remote connections
      replace:
        path: /etc/redis.conf
        regexp: '^bind 127.0.0.1'
        replace: 'bind 0.0.0.0'
 
    - name: Disable protected-mode
      replace:
        path: /etc/redis.conf
        regexp: '^protected-mode yes'
        replace: 'protected-mode no'
 
    - name: Start and enable Redis
      service:
        name: redis
        state: started
        enabled: yes