- name: Fix yum repos dynamically (CentOS / Stream safe)
  hosts: all
  become: yes
 
  tasks:
 
    - name: Find yum repo files
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: yum_repo_files
 
    - name: Show repo files found (debug)
      debug:
        msg: "{{ item.path }}"
      loop: "{{ yum_repo_files.files }}"
      when: yum_repo_files.matched > 0
 
    - name: Disable mirrorlist in repo files
      replace:
        path: "{{ item.path }}"
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
      loop: "{{ yum_repo_files.files }}"
      when: yum_repo_files.matched > 0
 
    - name: Enable CentOS Vault baseurl (CentOS Linux only)
      replace:
        path: "{{ item.path }}"
        regexp: '^#baseurl=http://mirror\.centos\.org'
        replace: 'baseurl=http://vault.centos.org'
      loop: "{{ yum_repo_files.files }}"
      when:
        - yum_repo_files.matched > 0
        - ansible_distribution == "CentOS"
        - ansible_distribution_release != "Stream"
 
    - name: Clean yum cache
      command: yum clean all
      changed_when: false