- name: Install and Configure Redis
  hosts: redis
  become: yes
 
  vars:
    redis_bind_address: 0.0.0.0
    redis_port: 6379
 
  tasks:
 
    ############################################################
    # FIX YUM REPOS (DYNAMIC & SAFE)
    ############################################################
    - name: Find yum repo files
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: yum_repo_files
 
    - name: Disable mirrorlist
      replace:
        path: "{{ item.path }}"
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
      loop: "{{ yum_repo_files.files }}"
      when: yum_repo_files.matched > 0
 
    - name: Enable CentOS Vault baseurl (CentOS Linux only)
      replace:
        path: "{{ item.path }}"
        regexp: '^#baseurl=http://mirror\.centos\.org'
        replace: 'baseurl=http://vault.centos.org'
      loop: "{{ yum_repo_files.files }}"
      when:
        - yum_repo_files.matched > 0
        - ansible_distribution == "CentOS"
        - ansible_distribution_release != "Stream"
 
    - name: Clean yum cache
      command: yum clean all
      changed_when: false
 
    ############################################################
    # INSTALL REMI
    ############################################################
    - name: Install Remi repository
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: yes
 
    - name: Enable Redis 6.2 module
      command: dnf module enable redis:remi-6.2 -y
      changed_when: false
 
    ############################################################
    # INSTALL REDIS
    ############################################################
    - name: Install Redis
      yum:
        name: redis
        state: present
 
    ############################################################
    # CONFIGURE REDIS
    ############################################################
    - name: Configure Redis bind address
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: "bind {{ redis_bind_address }}"
        backup: yes
 
    - name: Configure Redis port
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^port'
        line: "port {{ redis_port }}"
        backup: yes
 
    ############################################################
    # START SERVICE
    ############################################################
    - name: Start and enable Redis
      service:
        name: redis
        state: started
        enabled: yes