- name: Install and Configure Redis on CentOS 8
  hosts: redis
  become: yes
 
  vars:
    redis_bind_address: 0.0.0.0
    redis_port: 6379
 
  tasks:
 
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
 
    - name: Install Remi repository (CentOS 8)
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
        state: present
 
    - name: Enable Redis 6.2 module from Remi
      command: dnf module enable redis:remi-6.2 -y
      changed_when: false
 
    - name: Install Redis
      yum:
        name: redis
        state: present
 
    - name: Configure Redis bind address
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: "bind {{ redis_bind_address }}"
        backup: yes
 
    - name: Configure Redis port
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^port'
        line: "port {{ redis_port }}"
        backup: yes
 
    - name: Start and enable Redis service
      service:
        name: redis
        state: started
        enabled: yes