- name: Install and Configure Redis on CentOS 8 (Vault-safe)
  hosts: redis
  become: yes
 
  vars:
    redis_bind_address: 0.0.0.0
    redis_port: 6379
 
  tasks:
 
    ############################################################
    # FIX CENTOS 8 EOL REPOS
    ############################################################
    - name: Disable mirrorlist
      replace:
        path: /etc/yum.repos.d/CentOS-*.repo
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
 
    - name: Enable CentOS Vault repos
      replace:
        path: /etc/yum.repos.d/CentOS-*.repo
        regexp: '^#baseurl=http://mirror.centos.org'
        replace: 'baseurl=http://vault.centos.org'
 
    - name: Clean yum cache
      command: yum clean all
      changed_when: false
 
    ############################################################
    # INSTALL REMI (NO EPEL)
    ############################################################
    - name: Install Remi repository
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: yes
 
    - name: Enable Redis 6.2 module
      command: dnf module enable redis:remi-6.2 -y
      changed_when: false
 
    ############################################################
    # INSTALL REDIS
    ############################################################
    - name: Install Redis
      yum:
        name: redis
        state: present
 
    ############################################################
    # CONFIGURATION
    ############################################################
    - name: Configure Redis bind address
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: "bind {{ redis_bind_address }}"
        backup: yes
 
    - name: Configure Redis port
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^port'
        line: "port {{ redis_port }}"
        backup: yes
 
    ############################################################
    # SERVICE
    ############################################################
    - name: Start and enable Redis service
      service:
        name: redis
        state: started
        enabled: yes