- name: install shipping component
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: extract shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: Check if cities schema exists
    ansible.builtin.command: >
      mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }}
      -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='cities'"
    register: schema
    changed_when: false

  - name: Print schema status
    ansible.builtin.debug:
      msg: "Cities schema count = {{ schema.stdout }}"

  - name: Load schema.sql
    ansible.builtin.shell: >
      mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} < /app/db/schema.sql
    when: schema.stdout == "0"

  - name: Load app-user.sql
    ansible.builtin.shell: >
      mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} < /app/db/app-user.sql
    when: schema.stdout == "0"

  - name: Load master-data.sql
    ansible.builtin.shell: >
      mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} < /app/db/master-data.sql
    when: schema.stdout == "0"

  - name: Restart shipping service
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes